// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiglwywugztqjnexpmkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZ2x3eXd1Z3p0cWpuZXhwbWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjA5MTMsImV4cCI6MjA2MTM5NjkxM30.gWv3tC2rGq4OrJ7twr1oXGXjFrfNZGlWv3BRttgPd8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);